# Generated by Django 6.0.2 on 2026-04-25 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cithara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='songs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='3:00', max_length=10),
        ),
    ]
