# Generated by Django 6.0.2 on 2026-03-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cithara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='creator',
        ),
        migrations.AlterField(
            model_name='song',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='cithara.library'),
        ),
    ]
